name: Widgets CI

on:
  push:
    branches:
      - dev
      - master
      - rc
      - staging
    paths:
      - 'widgets/**'
      - '.github/workflows/widgets.yaml'
  pull_request:
    branches:
      - master
      - rc
      - dev
    paths:
      - 'widgets/**'

jobs:
  widgets:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-widgets-${{ hashFiles('yarn.lock', 'widgets/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-widgets-
            ${{ runner.os }}-yarn-

      - name: Clean Yarn cache
        run: yarn cache clean

      - name: Reinstall dependencies
        run: |
          rm -rf node_modules
          yarn install --force

      - name: Verify ts-loader installation
        run: yarn list --pattern ts-loader

      - name: List installed packages
        run: yarn list

      - name: Build
        run: |
          cd widgets
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' )
        run: |
          cd widgets
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker buildx build -t erxes/widgets:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/widgets:${GITHUB_REF#refs/heads/}
